#region Test Information
/*
* Test Name:
* Author:
* Purpose/Description:
* Creation Date:
* Version: 
* Updated By:
* Updated Date:
*/
#endregion

#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_Dashboard_FiveItems : ParentTest
    {
        ConnectUtility utility;
        public Connect_Dashboard_FiveItems(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect_Dashboard_FiveItems";  //Enter Test Name
            base.baseURL = url;  //Be sure to update the selenium.Open command with baseURL
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            base.description = "**Log in and validate that the last 5 activities are displayed. User is only in Test at present**";
            utility = new ConnectUtility(this);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(base.baseURL);
            utility.SignIn("gcreportautomation", "test1!");

            quality.IsTextPresent("Fri, May 15, 2009 5:33 AM");
            quality.IsTextPresent("Wed, Apr 22, 2009 6:34 AM");
            quality.IsTextPresent("Tue, Apr 21, 2009 7:08 PM");
            quality.IsTextPresent("Sun, Apr 19, 2009 6:08 PM");
            quality.IsTextPresent("Sat, Apr 18, 2009 12:23 PM");

            utility.SignOut();
        }
        #endregion


    }


}
