#region Test Information
/*
* Test Name:
* Author:
* Purpose/Description:
* Creation Date:
* Version: 
* Updated By:
* Updated Date:
*/
#endregion

#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_Dashboard_CreateGoal : ParentTest
    {
        ConnectUtility utility;
        public Connect_Dashboard_CreateGoal(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect_Dashboard_CreateGoal";  //Enter Test Name
            base.baseURL = url;  //Be sure to update the selenium.Open command with baseURL
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            base.description = "**Create a Goal from the Dashboard**";
            utility = new ConnectUtility(this);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(base.baseURL);
            //utility.SignIn("gctestuser011", "test1!");
            utility.CreateUser("test1!");
           
            Thread.Sleep(3000);
            quality.Click("id=navBarTabDashboard");
            quality.WaitForPageToLoad("30000");
            quality.Click("link=Create a new goal!");
            quality.WaitForPageToLoad("30000");
            quality.Type("id=ext-comp-1008", "Test Goal");
            quality.Type("id=ext-comp-1007", "8");
            quality.Click("id=saveGoalButton");
            quality.WaitForPageToLoad("30000");
            quality.IsTextPresent("Test Goal");
            quality.IsTextPresent("Any Activity Type");
            quality.IsTextPresent("8 hr");
            quality.IsTextPresent("6 Days");
            //quality.Click("css=div.ux-row-action-item.deleteGoal-icon");
            //quality.Click("id=ext-gen246");
            quality.WaitForPageToLoad("30000");
            utility.SignOut();

        }
        #endregion


    }


}
