#region Test Information
/*
* Test Name:
* Author:
* Purpose/Description:
* Creation Date:
* Version: 
* Updated By:
* Updated Date:
*/
#endregion

#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_Dashboard_ActivityType : ParentTest
    {
        ConnectUtility utility;
        public Connect_Dashboard_ActivityType(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect_Dashboard_ActivityType";  //Enter Test Name
            base.baseURL = url;  //Be sure to update the selenium.Open command with baseURL
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            base.description = "**Go to the dashboard and edit the Activity Type**";
            utility = new ConnectUtility(this);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(base.baseURL);
            utility.SignIn("gctestuser010", "test1!");
            ChangeActivityType("Uncategorized");
            ChangeActivityType("Running");
            ChangeActivityType("Street Running");
            ChangeActivityType("Track Running");
            ChangeActivityType("Trail Running");
            ChangeActivityType("Treadmill Running");
            ChangeActivityType("Cycling");
            ChangeActivityType("Cyclocross");
            ChangeActivityType("Downhill Biking");
            ChangeActivityType("Indoor Cycling");
            ChangeActivityType("Mountain Biking");
            ChangeActivityType("Recumbent Cycling");
            ChangeActivityType("Road Cycling");
            ChangeActivityType("Track Cycling");
            ChangeActivityType("Fitness Equipment");
            ChangeActivityType("Elliptical");
            ChangeActivityType("Indoor Cardio");
            ChangeActivityType("Indoor Rowing");
            ChangeActivityType("Stair Climbing");
            ChangeActivityType("Strength Training");
            ChangeActivityType("Hiking");
            ChangeActivityType("Swimming");
            ChangeActivityType("Lap Swimming");
            ChangeActivityType("Open Water Swimming");
            ChangeActivityType("Walking");
            ChangeActivityType("Casual Walking");
            ChangeActivityType("Speed Walking");
            ChangeActivityType("Transition");
            ChangeActivityType("Swim to Bike Transition");
            ChangeActivityType("Bike to Run Transition");
            ChangeActivityType("Run to Bike Transition");
            ChangeActivityType("Other");
            ChangeActivityType("Backcountry Skiing/Snowboarding");
            ChangeActivityType("Boating");
            ChangeActivityType("Cross Country Skiing");
            ChangeActivityType("Driving");
            ChangeActivityType("Flying");
            ChangeActivityType("Golf");
            ChangeActivityType("Horseback Riding");
            ChangeActivityType("Inline Skating");
            ChangeActivityType("Motorcycling");
            ChangeActivityType("Mountaineering");
            ChangeActivityType("Paddling");
            ChangeActivityType("Resort Skiing/Snowboarding");
            ChangeActivityType("Rowing");
            ChangeActivityType("Sailing");
            ChangeActivityType("Skate Skiing");
            ChangeActivityType("Skating");
            ChangeActivityType("Snowmobiling");
            ChangeActivityType("Snowshoeing");
            ChangeActivityType("Stand Up Paddleboarding");
            ChangeActivityType("Whitewater Kayaking/Rafting");
            ChangeActivityType("Wind/Kite Surfing");

            utility.SignOut();
            
        }
        #endregion

        public void ChangeActivityType(string type)
        {
            quality.Click("link=Quick Edit");
            quality.Select("id=activityTypeSelect1", type);
            quality.Click("link=Finish");
            Thread.Sleep(1000);
            quality.IsTextPresent(type);
        }
    }


}
