#region Test Information
/*
* Test Name:
* Author:
* Purpose/Description:
* Creation Date:
* Version: 
* Updated By:
* Updated Date:
*/
#endregion

#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Kenwood_ActivateYourMap_GetUnlockCode : ParentTest
    {
        KenwoodFunctions ken;
        public Kenwood_ActivateYourMap_GetUnlockCode(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "ActivateYourMap_GetUnlockCode";  //Enter Test Name
            base.baseURL = url;  //Be sure to update the selenium.Open command with baseURL
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            base.description = "**Enter an unlock code for maps**";
            ken = new KenwoodFunctions(quality, selenium);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(base.baseURL);

            quality.AreEqual("Garmin Product Updates for Kenwood", quality.GetTitle());
            quality.Click("//div[@id='bd']/div[6]/div[2]/div/div/a/span");
            quality.WaitForPageToLoad("30000");

            ken.ActivateMapPage();

            //comment: Type valid data and obtain the unlock code
            quality.Type("id=unitId", "3563850818");
            quality.Type("id=validationCode", validationCode);
            quality.Type("id=productKey", productKey);
            quality.Click("css=a.button > span");
            quality.WaitForPageToLoad("30000");

            ken.MapSuccessfullyActivatedPage();

        }
        #endregion


    }


}
