#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of Connect_SignIn****
    class Connect_MeasurementSettings : ParentTest
    {
        ConnectUtility utility;

        public Connect_MeasurementSettings(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect Measurement Settings";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.username = "gctestuser002";
            base.password = "test1!";
            base.description = "**This test logs and and changes to metric and back and makes sure the message is shown.**";
            quality = new QualityCheck(this);
            utility = new ConnectUtility(this);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            
            selenium.Open(baseURL);

            utility.SignIn(username, password);

            quality.Click("link=Settings");
            selenium.WaitForPageToLoad("30000");
            quality.Select("id=measurementCombo", "label=Metric");

            quality.CheckBodyForText("You successfully updated your Measurement Units");
            quality.Click("link=Dashboard");
            quality.Click("link=Settings");
            selenium.WaitForPageToLoad("30000");
            quality.Select("id=measurementCombo", "label=Statute");
                        //quality.Click("css=option[value=\"statute_us\"]");
            quality.CheckBodyForText("You successfully updated your Measurement Units");
            
            quality.Click("id=signOutLink");
            selenium.WaitForPageToLoad("30000");


        }
        #endregion

    }


}
