#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_UploadFile : ParentTest
    {
        ConnectUtility utility;
        public Connect_UploadFile(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect Upload File-Generic";  //Enter Test Name
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            utility = new ConnectUtility(this);
            base.password = "test1!";
            base.description = @"**This test creates a new account and uploads a single file, and verifies that the details can be viewed**";
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {

            selenium.Open(base.baseURL);
            utility.CreateUser(password);
            utility.UploadFile(@"C:\RegressionUpload\RunTwoStopsUseButton.TCX");
            utility.SignOut();
            //quality.Click("id=signOutLink");
            selenium.WaitForPageToLoad("30000");

        }
        #endregion


    }


}
