#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using Selenium;
#endregion


namespace SeleniumRegression
{
    class Connect_SignIn : ParentTest
    {

        ConnectUtility utility;

        public Connect_SignIn(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {           
            base.id = "Connect Basic Sign In";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.username = "gctestuser010";
            base.password = "test1!";
            base.description = @"**In this test a user logs in, checks to make sure they are, and logs out**";
            quality = new QualityCheck(this);
            utility = new ConnectUtility(this);
        }

        #region Run Test
        //this is the test code generated by selenium
        public override void RunTest()
        {
            base.RunTest();

            selenium.Open(baseURL);

            utility.SignIn(username, password);

            quality.IsTextPresent(username);

            if (base.IDPresent("signOutLink"))
            {
                selenium.Click("signOutLink");
            }
        }
        #endregion


    }

    
}
