#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_SignInValidation : ParentTest
    {

        ConnectUtility utility;

        public Connect_SignInValidation(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect SignIn Validation";  //Enter Test Name
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.description = "**This test tries invalid combination of username and passwords to check validations, then logs in and out**";
            quality = new QualityCheck(this);
            utility = new ConnectUtility(this);
            username = "gctestuser010";
            password = "test1!";

        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(baseURL);

            utility.SignIn(username, "");
           
            quality.IsTextPresent("Username and password are required");
            quality.Click("link=Sign In");
            utility.SignIn("", password);

            quality.IsTextPresent("Username and password are required");
            quality.Click("link=Sign In");
            utility.SignIn(username, "blah");

            quality.IsTextPresent("Invalid username/password combination");
            quality.Click("link=Sign In");
            utility.SignIn("blah", password);

            quality.IsTextPresent("Invalid username/password combination");
            quality.Click("link=Sign In");
            utility.SignIn(username, password);

            quality.IsTextPresent(username);

            quality.Click("id=signOutLink");
            selenium.WaitForPageToLoad("30000");
            //quality.IsTextPresent("You aren't signed in");
        }
        #endregion

        /*
        private void SignIn(string username, string password)
        {
            quality.Type("id=username", username);
            quality.Type("id=password", password);
            quality.Click("class=btn1");
            selenium.WaitForPageToLoad("30000");
        }
         */ 
    }


}
