#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using Selenium;
using System.IO;
#endregion

namespace SeleniumRegression
{
    class LocaleTest : ParentTest
    {
        Header header;
        Footer footer;
        HomePage homePage;
        CategoryPage categoryPage;
        ProductListPage productListPage;
        ProductPage productPage;


        public LocaleTest(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            base.id = "Locale Test";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;


        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        [Test]
        public override void RunTest()
        {
            header = new Header(selenium, this);
            footer = new Footer(selenium, this);
            homePage = new HomePage(selenium, this);
            categoryPage = new CategoryPage(selenium, this);
            productListPage = new ProductListPage(selenium, this);
            productPage = new ProductPage(selenium, this);

            homePage.openBEHomePage();
            //homePage.deleteCookies();
            homePage.verifyDutchText();
            header.verifyDutchText_CustomerNotLoggedIn();
            footer.clickFrenchLanguageLink();
            homePage.verifyFrenchText();
            header.verifyFrenchText_CustomerNotLoggedIn();
            footer.clickDutchLanguageLink();
            homePage.verifyDutchText();
            header.verifyDutchText_CustomerNotLoggedIn();
            //homePage.browseToCategoryOnTopMenu("du_On the Road");
            //driver.UnderlyingWebDriver.FindElement(By.TagName("Producten")).Click();
            categoryPage.verifyDutchText();
            footer.clickFrenchLanguageLink();
            categoryPage.verifyFrenchText();
            footer.clickDutchLanguageLink();
            categoryPage.verifyDutchText();

            string du_subCategory = "Autonavigatie";
            //driver.UnderlyingWebDriver.FindElement(By.  .ClassName("Producten")).Click();
            //driver.UnderlyingWebDriver.FindElement(By.TagName("Producten")).Click();
            //categoryPage.clickOnSubCategory(du_subCategory);
            //productListPage.verifyDutchText(du_subCategory, "Draagtas");

            footer.clickFrenchLanguageLink();
            productListPage.verifyFrenchText("fr_Automotive", "Etui de protection");
        }
        #endregion
    }
}
