#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using Selenium;
using System.IO;
#endregion

namespace SeleniumRegression
{
    class RegisterUserTest : ParentTest
    {

        HomePage homePage;
        Header header;
        SignInPage signInPage;
        CreateAccountPage createAccountPage;
        ManageAccountPage manageAccountPage;
        Customer customer;
        CreateAddressPage createAddressPage;


        public RegisterUserTest(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            base.id = "Register User Test";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;



        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        [Test]
        public override void RunTest()
        {

            homePage = new HomePage(selenium, this);
            header = new Header(selenium, this);
            signInPage = new SignInPage(selenium, this);
            createAccountPage = new CreateAccountPage(selenium, this);
            manageAccountPage = new ManageAccountPage(selenium, this);
            customer = createAccountPage.getCustomer();
            createAddressPage = new CreateAddressPage(customer, selenium, this);
            testRegisterUser_US();
            //testRegisterUser_UK();
            //testRegisterUser_BE();  //look into language links later.

        }
        #endregion


        public void testRegisterUser_US()
        {

            homePage.openUSHomePage();
            //homePage.deleteCookies();
            homePage.verifyCorrectPageIsDisplayed_US();
            header.clickOnMyAccountLink_US_UK();

            signInPage.verifyCorrectPageIsDisplayed_US_UK();
            signInPage.clickCreateNewAccountLink();

            createAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            createAccountPage.addCustomerInfo_US();

            manageAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            manageAccountPage.clickAddAddressBtn_US_UK();

            createAddressPage.verifyCorrectPageIsDisplayed_US_UK(false);
            createAddressPage.checkPreferredBillingAddressBox();
            createAddressPage.addAddress_US();

            manageAccountPage.verifyMyAddressBook(customer.getAddressList());
            selenium.UnderlyingWebDriver.FindElement(By.PartialLinkText("Account")).Click();
            manageAccountPage.clickAddAddressBtn_US_UK();
            createAddressPage = new CreateAddressPage(customer, selenium, this);
            createAddressPage.verifyCorrectPageIsDisplayed_US_UK(false);
            createAddressPage.enterCity("LA");
            createAddressPage.addAddress_US();

            manageAccountPage.verifyMyAddressBook(customer.getAddressList());

        }


        public void testRegisterUser_UK()
        {
            customer.setUserName("test_" + System.DateTime.Now.TimeOfDay.TotalMinutes);
            homePage.openUKHomePage();
            homePage.deleteCookies();
            homePage.verifyCorrectPageIsDisplayed_UK();
            header.clickOnMyAccountLink_US_UK();

            signInPage.verifyCorrectPageIsDisplayed_US_UK();
            signInPage.clickCreateNewAccountLink();

            createAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            createAccountPage.addCustomerInfo_UK();

            manageAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            manageAccountPage.clickAddAddressBtn_US_UK();

            createAddressPage.verifyCorrectPageIsDisplayed_US_UK(false);
            createAddressPage.addAddress_UK();

            manageAccountPage.verifyMyAddressBook(customer.getAddressList());
        }


        public void testRegisterUser_BE()
        {

            homePage.openBEHomePage();
            homePage.deleteCookies();
            homePage.verifyCorrectPageIsDisplayed_BE();
            customer.setUserName("test_" + System.DateTime.Now.TimeOfDay.TotalMinutes);
            header.clickOnMyAccountLink_BE();

            signInPage.verifyCorrectPageIsDisplayed_BE();
            signInPage.clickCreateNewAccountLink();

            createAccountPage.verifyCorrectPageIsDisplayed_BE();
            createAccountPage.addCustomerInfo_BE();

            manageAccountPage.verifyCorrectPageIsDisplayed_BE();
            manageAccountPage.clickAddAddressBtn_BE();

            createAddressPage.verifyCorrectPageIsDisplayed_BE(false);
            createAddressPage.addAddress_BE();

            manageAccountPage.verifyMyAddressBook(customer.getAddressList());
        }

    }
}
