#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using Selenium;
using System.IO;
#endregion

namespace SeleniumRegression
{
    class SingleSignOnLocaleTest : ParentTest
    {
        Header header;
        Footer footer;
        HomePage homePage;
        CategoryPage categoryPage;
        ProductListPage productListPage;
        ProductPage productPage;
        SignInPage signInPage;
        CreateAccountPage createAccountPage;
        ManageAccountPage manageAccountPage;
        Customer customer;
        CreateAddressPage createAddressPage;


        public SingleSignOnLocaleTest(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            base.id = "Single SignOn Locale Test";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;



        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        [Test]
        public override void RunTest()
        {
            header = new Header(selenium, this);
            footer = new Footer(selenium, this);
            homePage = new HomePage(selenium, this);
            categoryPage = new CategoryPage(selenium, this);
            productListPage = new ProductListPage(selenium, this);
            productPage = new ProductPage(selenium, this);
            signInPage = new SignInPage(selenium, this);
            createAccountPage = new CreateAccountPage(selenium, this);
            manageAccountPage = new ManageAccountPage(selenium, this);
            customer = createAccountPage.getCustomer();
            createAddressPage = new CreateAddressPage(customer, selenium, this);

            homePage.openBEHomePage();
            homePage.deleteCookies();
            homePage.openUSHomePage();
            homePage.deleteCookies();

            header.clickOnMyAccountLink_US_UK();
            signInPage.verifyCorrectPageIsDisplayed_US_UK();
            signInPage.clickCreateNewAccountLink();
            createAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            createAccountPage.addCustomerInfo_US();
            manageAccountPage.verifyCorrectPageIsDisplayed_US_UK();
            manageAccountPage.clickAddAddressBtn_US_UK();
            createAddressPage.verifyCorrectPageIsDisplayed_US_UK(false);
            createAddressPage.checkPreferredBillingAddressBox();
            createAddressPage.addAddress_US();

            String userName = customer.getUserName();

            homePage.openBEHomePage();
            homePage.verifyDutchText();//Below was commented out because the other language pages are not up to speed with US.  Also for SSO this seems like redundancy.  Needs to test integration with MyGarmin etc for SSO (IMO)
                                                    
            //header.verifyDutchText_CustomerLoggedIn(userName);
            /*
            footer.clickFrenchLanguageLink();
            homePage.verifyFrenchText();
            header.verifyFrenchText_CustomerLoggedIn(userName);
            footer.clickDutchLanguageLink();
            homePage.verifyDutchText();
            header.verifyDutchText_CustomerLoggedIn(userName);
            homePage.browseToCategoryOnTopMenu("du_On the Road");

            categoryPage.verifyDutchText();
            footer.clickFrenchLanguageLink();
            categoryPage.verifyFrenchText();
            footer.clickDutchLanguageLink();
            categoryPage.verifyDutchText();

            String du_subCategory = "du_Automotive";
            categoryPage.clickOnSubCategory(du_subCategory);
            productListPage.verifyDutchText(du_subCategory, "Draagtas");

            footer.clickFrenchLanguageLink();
            productListPage.verifyFrenchText("fr_Automotive", "Etui de protection");
            */

        }
        #endregion

    }
}
