#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class Connect_Navigation_Unauthenticated : ParentTest
    {
        ConnectUtility utility;
        public Connect_Navigation_Unauthenticated(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {        
	    //****Enter in Script Name here****  
            base.id = "Connect Navigation Unauthenticated";  //Enter Test Name
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
			base.quality = new QualityCheck(this);
            base.description = "**In this test a user doesn't log in and tries to view each page**";
            utility = new ConnectUtility(this);
        }
     
#region Test Script
        //this is the test code generated by selenium
	//****Paste test script here*****
        public override void RunTest()
        {
            quality.Click("headerSignInLink");

            quality.Click("link=Analyze");
            quality.IsTextNotPresent("All your activities in one place");

            quality.Click("link=Plan");
            quality.IsTextNotPresent("Make the most of your busy schedule");

            quality.Click("link=Plan");
            
        }
#endregion

 
    }

    
}
