#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using Selenium;
using Selenium.Internal.SeleniumEmulation;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of Connect_SignIn****
    class Connect_GeneralNavigation : ParentTest
    {

        ConnectUtility utility;
        #region Test Constructor
        public Connect_GeneralNavigation(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Connect_General Navigation";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.username = "gctestuser010";
            base.password = "test1!";
            base.quality = new QualityCheck(this);
            base.description = "**This test has a user log in, go to each page and make sure the header text is displayed**";
            utility = new ConnectUtility(this);
        }
        #endregion

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {

            selenium.Open(baseURL);

            utility.SignIn(username, password);
            quality.IsTextPresent(username);

            quality.Click("link=Analyze");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("All your activities in one place");

            quality.Click("link=Reports");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("See how your statistics add up");


            quality.Click("link=Health");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("Keep track of your health");

            quality.Click("link=Plan");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("Make the most of your busy schedule");


            quality.Click("link=Courses");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("Courses");

            quality.Click("link=Workouts");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("Plan and create your fitness routines");

            quality.Click("link=Goals");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("Set an objective and stay on target with Garmin Connect.");

            quality.Click("signOutLink");
            selenium.WaitForPageToLoad("30000");
            quality.IsTextPresent("You aren't signed in");

        }
        #endregion        
    }
}
