#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of Connect_SignIn****
    class Buy_PurchaseTest : ParentTest
    {
        public Buy_PurchaseTest(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Buy Purchase Test!!!";
            base.baseURL = url;
            base.selenium = webdriver;
            base.verificationErrors = verrors;

        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {

            selenium.Open(baseURL);
            selenium.Click("link=+ On the Road");
            selenium.WaitForPageToLoad("30000");
            selenium.Click("css=div.tab-content.clear > ul > li > a > span");
            selenium.WaitForPageToLoad("30000");
            base.LinkValuePresent("link=2012 nüvi Lineup", "2012 nüvi Lineup");
            selenium.Click("link=2012 nüvi Lineup");
            selenium.WaitForPageToLoad("30000");
            base.IsTextPresent("NÜVI 30/40/50 SERIES");
            /*
            try
            {
                Assert.IsTrue(driver.IsTextPresent("NÜVI 30/40/50 SERIES"));
            }
            catch (AssertionException e)
            {
                base.IsTextPresent(driver, "NÜVI 30/40/50 SERIES");
                verificationErrors.Append(e.Message);
            }
             */ 
            selenium.Click("link=Guidance 2.0/3.0");
            selenium.WaitForPageToLoad("30000");
            selenium.Click("css=img[alt=\"Garmin\"]");
            selenium.WaitForPageToLoad("30000");


        }
        #endregion

    }


}
