#region Test Information
/*
* Test Name:
* Author:
* Purpose/Description:
* Creation Date:
* Version: 
* Updated By:
* Updated Date:
*/
#endregion

#region Using Statements
using System;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Linq;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using System.Web;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Drawing;
using Selenium;
#endregion


namespace SeleniumRegression
{
    //****Enter in desired test name in replace of EnterClassName****
    class TheKenwood_CreateAccount_NewUserTest : ParentTest
    {
        KenwoodFunctions ken;

        public TheKenwood_CreateAccount_NewUserTest(string url, WebDriverBackedSelenium webdriver, StringBuilder verrors)
        {
            //****Enter in Script Name here****  
            base.id = "Create New User";  //Enter Test Name
            base.baseURL = url;  //Be sure to update the selenium.Open command with baseURL
            base.selenium = webdriver;
            base.verificationErrors = verrors;
            base.quality = new QualityCheck(this);
            base.description = "**Validates creating a new account**";
            ken = new KenwoodFunctions(quality, selenium);
        }

        #region Test Script
        //this is the test code generated by selenium
        //****Paste test script here*****
        public override void RunTest()
        {
            selenium.Open(base.baseURL);

            //set speed to lower value
            //selenium.SetSpeed("300");

            ken.WelcomePage();

            quality.Click("link=Sign In");
            quality.WaitForPageToLoad("30000");

            ken.SignInPage();

            // comment: Validate the Create Account page
            quality.Click("css=div.left > a.button > span");
            quality.WaitForPageToLoad("30000");

            // comment: Validate the Create Account page
            ken.CreateAccountPage();

            // comment: Enter valid information
            quality.Type("id=fullName", "full name");
            quality.Type("id=username", "newTestUser" + ken.RandomString(4));
            quality.Type("id=address", "home address");
            quality.Type("id=password", password);
            quality.Type("id=address2", "office address");
            quality.Type("id=retypePassword", password);
            quality.Type("id=city", "my city");
            quality.Select("id=state", "label=Hawaii");

            string random1 = ken.RandomString(4);
            string random2 = ken.RandomString(4);

            quality.Type("id=email", random1 + "." + random2 + "@garmin.com");
            quality.Type("id=retypeEmail", random1 + "." + random2 + "@garmin.com");

            quality.Select("id=country", "label=United States");
            quality.Type("id=zip", "988745");

            quality.Click("//form[@id='createAccountForm']/table/tbody/tr[8]/td/a[2]/span");
            quality.WaitForPageToLoad("30000");

            Thread.Sleep(5000);

            quality.AreEqual("Garmin Product Updates for Kenwood", selenium.GetTitle());
            quality.AreEqual("Welcome full name", selenium.GetText("css=span.margin-lr5"));
            quality.AreEqual("Sign Out", quality.GetText("link=Sign Out"));

            // comment: Sign Out
            ken.Logout();

        }
        #endregion
        
    }
}
